# Generated by Django 4.0.4 on 2022-05-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_foundation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='foundation_year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
