# Generated by Django 4.0.4 on 2022-05-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
